BZ #1715084 - NoMethodError: undefined method `storage_domain' for nil:NilClass
Fixes #26919 - Resolve nil error in ovirt disk clone

(cherry picked from commit 10c89053e3a3d933c28ff37b13a93e9e37697b90)